/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka.advanced.exercise9;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroObservation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7006806970297843159L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroObservation\",\"namespace\":\"kafka.advanced.exercise9\",\"fields\":[{\"name\":\"value\",\"type\":\"double\",\"doc\":\"The value of the Observation\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"The timestamp of the Observation\"},{\"name\":\"observationType\",\"type\":{\"type\":\"enum\",\"name\":\"AvroObservationType\",\"symbols\":[\"TEMPERATURE\",\"HUMIDITY\",\"PRESSURE\"]},\"doc\":\"The type of the Observation\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroObservation> ENCODER =
      new BinaryMessageEncoder<AvroObservation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroObservation> DECODER =
      new BinaryMessageDecoder<AvroObservation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroObservation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroObservation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroObservation>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroObservation to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroObservation from a ByteBuffer. */
  public static AvroObservation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The value of the Observation */
  @Deprecated public double value;
  /** The timestamp of the Observation */
  @Deprecated public long timestamp;
  /** The type of the Observation */
  @Deprecated public kafka.advanced.exercise9.AvroObservationType observationType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroObservation() {}

  /**
   * All-args constructor.
   * @param value The value of the Observation
   * @param timestamp The timestamp of the Observation
   * @param observationType The type of the Observation
   */
  public AvroObservation(java.lang.Double value, java.lang.Long timestamp, kafka.advanced.exercise9.AvroObservationType observationType) {
    this.value = value;
    this.timestamp = timestamp;
    this.observationType = observationType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    case 1: return timestamp;
    case 2: return observationType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.Double)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: observationType = (kafka.advanced.exercise9.AvroObservationType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the Observation
   */
  public java.lang.Double getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * The value of the Observation
   * @param value the value to set.
   */
  public void setValue(java.lang.Double value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The timestamp of the Observation
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * The timestamp of the Observation
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'observationType' field.
   * @return The type of the Observation
   */
  public kafka.advanced.exercise9.AvroObservationType getObservationType() {
    return observationType;
  }

  /**
   * Sets the value of the 'observationType' field.
   * The type of the Observation
   * @param value the value to set.
   */
  public void setObservationType(kafka.advanced.exercise9.AvroObservationType value) {
    this.observationType = value;
  }

  /**
   * Creates a new AvroObservation RecordBuilder.
   * @return A new AvroObservation RecordBuilder
   */
  public static kafka.advanced.exercise9.AvroObservation.Builder newBuilder() {
    return new kafka.advanced.exercise9.AvroObservation.Builder();
  }

  /**
   * Creates a new AvroObservation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroObservation RecordBuilder
   */
  public static kafka.advanced.exercise9.AvroObservation.Builder newBuilder(kafka.advanced.exercise9.AvroObservation.Builder other) {
    return new kafka.advanced.exercise9.AvroObservation.Builder(other);
  }

  /**
   * Creates a new AvroObservation RecordBuilder by copying an existing AvroObservation instance.
   * @param other The existing instance to copy.
   * @return A new AvroObservation RecordBuilder
   */
  public static kafka.advanced.exercise9.AvroObservation.Builder newBuilder(kafka.advanced.exercise9.AvroObservation other) {
    return new kafka.advanced.exercise9.AvroObservation.Builder(other);
  }

  /**
   * RecordBuilder for AvroObservation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroObservation>
    implements org.apache.avro.data.RecordBuilder<AvroObservation> {

    /** The value of the Observation */
    private double value;
    /** The timestamp of the Observation */
    private long timestamp;
    /** The type of the Observation */
    private kafka.advanced.exercise9.AvroObservationType observationType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(kafka.advanced.exercise9.AvroObservation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.observationType)) {
        this.observationType = data().deepCopy(fields()[2].schema(), other.observationType);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroObservation instance
     * @param other The existing instance to copy.
     */
    private Builder(kafka.advanced.exercise9.AvroObservation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.observationType)) {
        this.observationType = data().deepCopy(fields()[2].schema(), other.observationType);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'value' field.
      * The value of the Observation
      * @return The value.
      */
    public java.lang.Double getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * The value of the Observation
      * @param value The value of 'value'.
      * @return This builder.
      */
    public kafka.advanced.exercise9.AvroObservation.Builder setValue(double value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * The value of the Observation
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'value' field.
      * The value of the Observation
      * @return This builder.
      */
    public kafka.advanced.exercise9.AvroObservation.Builder clearValue() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * The timestamp of the Observation
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * The timestamp of the Observation
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public kafka.advanced.exercise9.AvroObservation.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * The timestamp of the Observation
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * The timestamp of the Observation
      * @return This builder.
      */
    public kafka.advanced.exercise9.AvroObservation.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'observationType' field.
      * The type of the Observation
      * @return The value.
      */
    public kafka.advanced.exercise9.AvroObservationType getObservationType() {
      return observationType;
    }

    /**
      * Sets the value of the 'observationType' field.
      * The type of the Observation
      * @param value The value of 'observationType'.
      * @return This builder.
      */
    public kafka.advanced.exercise9.AvroObservation.Builder setObservationType(kafka.advanced.exercise9.AvroObservationType value) {
      validate(fields()[2], value);
      this.observationType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'observationType' field has been set.
      * The type of the Observation
      * @return True if the 'observationType' field has been set, false otherwise.
      */
    public boolean hasObservationType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'observationType' field.
      * The type of the Observation
      * @return This builder.
      */
    public kafka.advanced.exercise9.AvroObservation.Builder clearObservationType() {
      observationType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroObservation build() {
      try {
        AvroObservation record = new AvroObservation();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.Double) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.observationType = fieldSetFlags()[2] ? this.observationType : (kafka.advanced.exercise9.AvroObservationType) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroObservation>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroObservation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroObservation>
    READER$ = (org.apache.avro.io.DatumReader<AvroObservation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
