/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package exercise9;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AvroObservationType {
  ROOM, BUILDING, PARK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroObservationType\",\"namespace\":\"exercise9\",\"symbols\":[\"ROOM\",\"BUILDING\",\"PARK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
